Update user-manual.md - Settings Screen
sspanak/tt9 pull request #178
Opened 2023-02-10 04:47 UTC by justbruce

Add 2 additional methods to reach the settings screen as suggested by @sspanak

2023-02-10 04:57 UTC, justbruce reviewed
corrected the Default settings screen key to "Hold *"

2023-02-10 09:03 UTC, sspanak requested changes

2023-02-10 09:03 UTC, sspanak commented on docs/user-manual.md
> +- Press the Assigned Hotkey [Default: Hold *]
```suggestion
- Start typing in a text field to wake up TT9.
- Use the assigned hotkey [Default: Hold ✱].
```

2023-02-10 09:03 UTC, sspanak commented on docs/user-manual.md
> +- Thru Android Settings: System -> Languages -> (On-screen) Keyboard(s) -> Traditional T9.
Let's extend this a bit:

```suggestion
- Go to Android Settings → System → Languages → Keyboards (or On-Screen Keyboards). This is where all installed keyboards are configured.
- Select "Traditional T9".

_The actual menu names may vary depending on your phone, Android version and language._
```

2023-02-10 09:03 UTC, sspanak commented on docs/user-manual.md
>  To access it:
```suggestion
### How to access the Settings?
```

2023-02-10 09:05 UTC, sspanak commented
I actually already fixed it, but your version seems to be shorter and more clear. Let's use a mixture of both.

2023-02-13 09:07 UTC, sspanak commented on docs/user-manual.md
>  - Use the on-screen gear button or press the Settings Key.
```suggestion
- Use the on-screen gear button.
```

2023-02-13 09:08 UTC, sspanak approved these changes

2023-02-13 09:10 UTC, merged